# Generated by Django 5.0.14 on 2026-09-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('obl_id', models.IntegerField()),
                ('area_id', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('token', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('citizen', "Fuqaro ma'lumotlari"), ('family', "Oila a'zolari")], default='citizen', max_length=20)),
                ('streets', models.JSONField(default=list)),
                ('static_fields', models.JSONField(default=dict)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('stats', models.JSONField(default=dict)),
                ('done_ids', models.JSONField(default=list)),
                ('logs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.mahalla')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kadastr', models.CharField(db_index=True, max_length=100)),
                ('pinfl', models.CharField(blank=True, default='', max_length=20)),
                ('birth_date', models.CharField(blank=True, default='', max_length=20)),
                ('mahalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.mahalla')),
            ],
            options={
                'indexes': [models.Index(fields=['mahalla', 'kadastr'], name='core_citize_mahalla_cc1336_idx')],
            },
        ),
    ]
