# Generated by Django 5.0.14 on 2026-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahalla',
            name='ihma_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
